<?php
/**
 * Comments listing for single post.
 *
 * @package    BardCanvas
 * @subpackage comments
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 *
 * Imported globals:
 * @var post_record $post
 *
 * Trailing vars:
 * @var module           $this_module    self (comments)
 * @var module           $current_module posts
 * @var comment_record[] $comments
 */

use hng2_base\module;
use hng2_modules\comments\comment_record;
use hng2_modules\posts\post_record;
?>

<section class="comments_list">
    Estos son los comentarios
</section>

